name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          token: ${{ secrets.ORG_GH_RELEASE_TOKEN }}
      - run: yarn install --frozen-lockfile
      - run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn install --frozen-lockfile
      - run: yarn test:coverage
#      - run: yarn codecov -t $CODECOV_TOKEN
#        env:
#          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  release:
    if: contains(github.ref, 'master') && !contains(github.event.head_commit.message, '[ci skip]')
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Git identity
        run: |
          git config --local user.name 'Robotic Condor [bot]'
          git config --local user.email 'bot@radicalcondor.dev'
          git remote set-url origin https://roboticcondor:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git
        env:
          GH_TOKEN: ${{ secrets.ORG_GH_RELEASE_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Create .npmrc
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.ORG_NPM_RELEASE_TOKEN }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Publish all packages with Lerna
        run: yarn release
        env:
          GH_TOKEN: ${{ secrets.ORG_GH_RELEASE_TOKEN }}
